import psycopg2

def write_image(facid,file_path):

    img =  open(file_path, "rb").read()

    conn = psycopg2.connect("postgresql://postgres:postgres@localhost:5432/licenta")
    crsr = conn.cursor()
    try :
        
            crsr.execute("UPDATE Facs SET facimg = %s WHERE facid = %s", (psycopg2.Binary(img), facid))
            conn.commit()
        
    except (Exception, psycopg2.DatabaseError) as error:
        
            print(error)
    finally:
           conn.close()
        


write_image(1, "A:/FACULTATE/LICENTA/static/facultati/UPB/upb-automatica.png")
write_image(2, "A:/FACULTATE/LICENTA/static/facultati/UPB/upb-automatica.png")
write_image(3, "A:/FACULTATE/LICENTA/static/facultati/UPB/upb-automatica.png")
write_image(4, "A:/FACULTATE/LICENTA/static/facultati/UPB/upb-automatica.png")
write_image(5, "A:/FACULTATE/LICENTA/static/facultati/UPB/inginerie_electrica_upb.png")
write_image(6, "A:/FACULTATE/LICENTA/static/facultati/UPB/energetica_upb.png")
write_image(7, "A:/FACULTATE/LICENTA/static/facultati/UPB/etti.png")
write_image(8, "A:/FACULTATE/LICENTA/static/facultati/UPB/etti.png")
write_image(9, "A:/FACULTATE/LICENTA/static/facultati/UPB/inginerie_mecanica_si_mecatronica_upb.png")
write_image(10, "A:/FACULTATE/LICENTA/static/facultati/UPB/inginerie_industriala_si_robotica_upb.png")
write_image(11, "A:/FACULTATE/LICENTA/static/facultati/UPB/ingineria_sistemelor_biotehnice_upb.png")
write_image(12, "A:/FACULTATE/LICENTA/static/facultati/UPB/transporturi_upb.png")
write_image(13, "A:/FACULTATE/LICENTA/static/facultati/UPB/aerospatiala_upb.png")
write_image(14, "A:/FACULTATE/LICENTA/static/facultati/UPB/stiinta_si_ingineria_materialelor_upb.png")
write_image(15, "A:/FACULTATE/LICENTA/static/facultati/UPB/inginerie_chimica_si_biotehnologii_upb.png")
write_image(16, "A:/FACULTATE/LICENTA/static/facultati/UPB/inginerie_in_limbi_straine.png")
write_image(17, "A:/FACULTATE/LICENTA/static/facultati/UPB/stiinte_aplicate.png")
write_image(18, "A:/FACULTATE/LICENTA/static/facultati/UPB/inginerie_medicala_upb.png")
write_image(19, "A:/FACULTATE/LICENTA/static/facultati/UPB/facultatea_FAIMA.png")
write_image(20, "A:/FACULTATE/LICENTA/static/facultati/ASE/administrarea_afacerilor.png")
write_image(21, "A:/FACULTATE/LICENTA/static/facultati/ASE/administrarea_afacerilor.png")
write_image(22, "A:/FACULTATE/LICENTA/static/facultati/ASE/administratie_si_management_public.png")
write_image(23, "A:/FACULTATE/LICENTA/static/facultati/ASE/administratie_si_management_public.png")
write_image(24, "A:/FACULTATE/LICENTA/static/facultati/ASE/business_si_turism.png")
write_image(25, "A:/FACULTATE/LICENTA/static/facultati/ASE/CSIE.png")
write_image(26, "A:/FACULTATE/LICENTA/static/facultati/ASE/CSIE.png")
write_image(27, "A:/FACULTATE/LICENTA/static/facultati/ASE/CSIE.png")
write_image(28, "A:/FACULTATE/LICENTA/static/facultati/ASE/CSIE.png")
write_image(29, "A:/FACULTATE/LICENTA/static/facultati/ASE/CSIE.png")
write_image(30, "A:/FACULTATE/LICENTA/static/facultati/ASE/CSIE.png")
write_image(31, "A:/FACULTATE/LICENTA/static/facultati/ASE/CSIE.png")
write_image(32, "A:/FACULTATE/LICENTA/static/facultati/ASE/CSIE.png")
write_image(33, "A:/FACULTATE/LICENTA/static/facultati/ASE/contabilitate_informatica.png")
write_image(34, "A:/FACULTATE/LICENTA/static/facultati/ASE/contabilitate_informatica.png")
write_image(35, "A:/FACULTATE/LICENTA/static/facultati/ASE/drept_ASE.png")
write_image(36, "A:/FACULTATE/LICENTA/static/facultati/ASE/drept_ASE.png")
write_image(37, "A:/FACULTATE/LICENTA/static/facultati/ASE/economie_teoretica_si_aplicata.png")
write_image(38, "A:/FACULTATE/LICENTA/static/facultati/ASE/economie_teoretica_si_aplicata.png")
write_image(39, "A:/FACULTATE/LICENTA/static/facultati/ASE/economie_agroalimentara.png")
write_image(40, "A:/FACULTATE/LICENTA/static/facultati/ASE/economie_agroalimentara.png")
write_image(41, "A:/FACULTATE/LICENTA/static/facultati/ASE/finante_asigurari.png")
write_image(42, "A:/FACULTATE/LICENTA/static/facultati/ASE/finante_asigurari.png")
write_image(43, "A:/FACULTATE/LICENTA/static/facultati/ASE/finante_asigurari.png")
write_image(44, "A:/FACULTATE/LICENTA/static/facultati/ASE/finante_asigurari.png")
write_image(45, "A:/FACULTATE/LICENTA/static/facultati/ASE/management.png")
write_image(46, "A:/FACULTATE/LICENTA/static/facultati/ASE/management.png")
write_image(47, "A:/FACULTATE/LICENTA/static/facultati/ASE/management.png")
write_image(48, "A:/FACULTATE/LICENTA/static/facultati/ASE/management.png")
write_image(49, "A:/FACULTATE/LICENTA/static/facultati/ASE/marketing.png")
write_image(50, "A:/FACULTATE/LICENTA/static/facultati/ASE/marketing.png")
write_image(51, "A:/FACULTATE/LICENTA/static/facultati/ASE/marketing.png")
write_image(52, "A:/FACULTATE/LICENTA/static/facultati/ASE/marketing.png")
write_image(53, "A:/FACULTATE/LICENTA/static/facultati/ASE/relatii_economice.png")
write_image(54, "A:/FACULTATE/LICENTA/static/facultati/ASE/relatii_economice.png")
write_image(55, "A:/FACULTATE/LICENTA/static/facultati/ASE/relatii_economice.png")
write_image(56, "A:/FACULTATE/LICENTA/static/facultati/ASE/relatii_economice.png")
write_image(57, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(58, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(59, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(60, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(61, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(62, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(63, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(64, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(65, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(66, "A:/FACULTATE/LICENTA/static/facultati/UMFCD/medicina.png")
write_image(67, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/Administratie-si-Afaceri.png")
write_image(68, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/Administratie-si-Afaceri.png")
write_image(69, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/biologie_unibuc.png")
write_image(70, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/biologie_unibuc.png")
write_image(71, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/chimie.png")
write_image(72, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/chimie.png")
write_image(73, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/drept_unibuc.png")
write_image(74, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/filosofie.png")
write_image(75, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/filosofie.png")
write_image(76, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/fizica.png")
write_image(77, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/geografie.png")
write_image(78, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/geografie.png")
write_image(79, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/geologie_si_geofizica.png")
write_image(80, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/geologie_si_geofizica.png")
write_image(81, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/geologie_si_geofizica.png")
write_image(82, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/geologie_si_geofizica.png")
write_image(83, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/geologie_si_geofizica.png")
write_image(84, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/geologie_si_geofizica.png")
write_image(85, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/istorie.png")
write_image(86, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/jurnalism.png")
write_image(87, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/limbi_straine.png")
write_image(88, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/limbi_straine.png")
write_image(89, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/litere.png")
write_image(90, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/litere.png")
write_image(91, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/fmi.png")
write_image(92, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/fmi.png")
write_image(93, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/fmi.png")
write_image(94, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/fmi.png")
write_image(95, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/fmi.png")
write_image(96, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/fmi.png")
write_image(97, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/psihologie.png")
write_image(98, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/asistenta_sociala.png")
write_image(99, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/asistenta_sociala.png")
write_image(100, "A:/FACULTATE/LICENTA/static/facultati/UNIBUC/stiinte_politice.png")
write_image(101, "A:/FACULTATE/LICENTA/static/facultati/IASI/biologie.png")
write_image(102, "A:/FACULTATE/LICENTA/static/facultati/IASI/biologie.png")
write_image(103, "A:/FACULTATE/LICENTA/static/facultati/IASI/chimie.png")
write_image(104, "A:/FACULTATE/LICENTA/static/facultati/IASI/chimie.png")
write_image(105, "A:/FACULTATE/LICENTA/static/facultati/IASI/drept.png")
write_image(106, "A:/FACULTATE/LICENTA/static/facultati/IASI/drept.png")
write_image(107, "A:/FACULTATE/LICENTA/static/facultati/IASI/economie_si_administrarea_afacerilor.png")
write_image(108, "A:/FACULTATE/LICENTA/static/facultati/IASI/economie_si_administrarea_afacerilor.png")
write_image(109, "A:/FACULTATE/LICENTA/static/facultati/IASI/sport.png")
write_image(110, "A:/FACULTATE/LICENTA/static/facultati/IASI/sport.png")
write_image(111, "A:/FACULTATE/LICENTA/static/facultati/IASI/sport.png")
write_image(112, "A:/FACULTATE/LICENTA/static/facultati/IASI/sport.png")
write_image(113, "A:/FACULTATE/LICENTA/static/facultati/IASI/filosofie.png")
write_image(114, "A:/FACULTATE/LICENTA/static/facultati/IASI/filosofie.png")
write_image(115, "A:/FACULTATE/LICENTA/static/facultati/IASI/filosofie.png")
write_image(116, "A:/FACULTATE/LICENTA/static/facultati/IASI/filosofie.png")
write_image(117, "A:/FACULTATE/LICENTA/static/facultati/IASI/fizica.png")
write_image(118, "A:/FACULTATE/LICENTA/static/facultati/IASI/fizica.png")
write_image(119, "A:/FACULTATE/LICENTA/static/facultati/IASI/fizica.png")
write_image(120, "A:/FACULTATE/LICENTA/static/facultati/IASI/geografie.png")
write_image(121, "A:/FACULTATE/LICENTA/static/facultati/IASI/informatica.png")
write_image(122, "A:/FACULTATE/LICENTA/static/facultati/IASI/informatica.png")
write_image(123, "A:/FACULTATE/LICENTA/static/facultati/IASI/informatica.png")
write_image(124, "A:/FACULTATE/LICENTA/static/facultati/IASI/informatica.png")
write_image(125, "A:/FACULTATE/LICENTA/static/facultati/IASI/Istorie.png")
write_image(126, "A:/FACULTATE/LICENTA/static/facultati/IASI/Istorie.png")
write_image(127, "A:/FACULTATE/LICENTA/static/facultati/IASI/litere.png")
write_image(128, "A:/FACULTATE/LICENTA/static/facultati/IASI/litere.png")
write_image(129, "A:/FACULTATE/LICENTA/static/facultati/IASI/matematica.png")
write_image(130, "A:/FACULTATE/LICENTA/static/facultati/IASI/matematica.png")
write_image(131, "A:/FACULTATE/LICENTA/static/facultati/IASI/matematica.png")
write_image(132, "A:/FACULTATE/LICENTA/static/facultati/IASI/matematica.png")
write_image(133, "A:/FACULTATE/LICENTA/static/facultati/IASI/psihologie.png")
write_image(134, "A:/FACULTATE/LICENTA/static/facultati/IASI/psihologie.png")
